# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    twig:
        mode: lazy
    resolvers:
        default:
            web_path: ~

    webp:
        generate: true

    filter_sets:
        cache: ~
        banner:
            quality: 75
            filters:
                thumbnail: { size: [1200, 400], mode: outbound }
#                background: { size: [124, 94], position: center, color: '#000000' }

        blog_image:
            quality: 100
            filters:
                thumbnail: { size: [360, 240], mode: outbound }

        blog_banner:
            quality: 75
            filters:
                thumbnail: { size: [1000, 350], mode: outbound }

        partner:
            quality: 75
            filters:
                thumbnail: { size: [168, 34], mode: outbound }