<?php

namespace App\Controller\Admin;

use App\Entity\HomeBanner;
use EasyCorp\Bundle\EasyAdminBundle\Config\Crud;
use EasyCorp\Bundle\EasyAdminBundle\Controller\AbstractCrudController;
use EasyCorp\Bundle\EasyAdminBundle\Field\IdField;
use EasyCorp\Bundle\EasyAdminBundle\Field\ImageField;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextEditorField;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextField;
use Vich\UploaderBundle\Form\Type\VichImageType;

class HomeBannerCrudController extends AbstractCrudController
{
    public const UPLOAD_BANNER_BASE_PATH = 'uploads/images/home_banners';
    public const UPLOAD_BANNER_ROOT_PATH = 'public/uploads/images/home_banners';
    public static function getEntityFqcn(): string
    {
        return HomeBanner::class;
    }

    public function configureCrud(Crud $crud): Crud
    {
        return parent::configureCrud($crud)
            ->setPageTitle('index', 'Gestion des bannières d\'accueil')
            ->setPageTitle('new', 'Ajouter une nouvelle bannière à la une'); // TODO: Change the autogenerated stub
    }

    public function configureFields(string $pageName): iterable
    {
        return [
            IdField::new('id')->onlyOnIndex(),
            TextField::new('title', 'Titre'),
            TextField::new('caption', 'Premier Descriptif'),
            TextField::new('secondCaption', 'Deuxième Descriptif'),
            TextField::new('imageFile', 'Illustration')
                ->hideOnIndex()
                ->setFormType(VichImageType::class)->setColumns('col-sm-12 col-md-3'),
            ImageField::new('bannerImage', 'Illustration')
                ->hideOnForm()
                ->setBasePath(self::UPLOAD_BANNER_BASE_PATH)
                ->setUploadDir(self::UPLOAD_BANNER_ROOT_PATH)
                ->setSortable(false),
        ];
    }
}
