# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    path.post_images: 'uploads/images/posts'
    path.member_images: 'uploads/images/users'
    path.home_banners: 'uploads/images/home_banners'
    path.testimonies: 'uploads/images/testimonies'
    path.services: 'uploads/images/services'
    path.services.icons: 'uploads/images/services/icons'
    path.prestations.icons: 'uploads/images/prestations/icons'
    path.our_work: 'uploads/images/our_works'
    path.partners: 'uploads/images/partners'
    contact_mail: '%env(CONTACT_EMAIL)%'
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
